### ISSUE TITLE
Error al decrementar stock en el proceso de compra

### ISSUE THREAD

**Issue by earias08** [alejandrobusi/Todo1-Ecommerce#10]
Se pueden seleccionar mayor cantidad de productos de los que figuran en el stock actual, en el momento de efectuar la compra solo se resta 1 producto del stock

![image](https://user-images.githubusercontent.com/18445151/184383418-d917f1d5-8372-45cf-8682-6a9e2980922b.png)

**Comment by pedroginel** [comment]
Hola Emilse

Ya arreglamos la interaccion que provocaba que el stock se vuelva negativo (osea que se puedan agregar mas productos que los que habia en stock). Tambien chequie realizar una compra y el stock de los productos se actualiza bien para mi.
