### ISSUE TITLE
No se puede eliminar un producto cargado al carrito desde la pagina de detalle del producto

### ISSUE THREAD

**Issue by earias08** [alejandrobusi/Todo1-Ecommerce#13]
- Al seleccionar el botón quitar de la página de detalle, se produce un erro al intentar eliminar el producto.
- Además agregar el mismo efecto al botón añadir al carrito como se ve en la página principal, ya que no hay algo que indique si el producto se agregó correctamente al carrito desde la web de detalle del producto.

![image](https://user-images.githubusercontent.com/18445151/184384047-1e7f57a3-42a4-43b6-a882-124d9760aa4c.png)

**Comment by pedroginel** [comment]
- El boton señalado en el screenshot no servia para eliminar productos del carrito. Este boton en realidad era para agregar o quitar productos de la lista de favoritas del usuario. Ya que la funcion de la lista de favoritos no era un requisito para la pagina, decidimos quitarla. Pero algunos botones parecen haber quedado sin eliminar, ya arreglamos este problema, eliminando todos los botones que quedaban aun en la pagina.

- Por otro lado, tambien agregamos efecto al boton añadir. Para mostrar cuando algún producto ya fue agregado al carrito (Ahora muestra un badge rojo, al igual que en la lista de productos).
