### ISSUE TITLE
Corregir maquetado

### ISSUE THREAD

**Issue by earias08** [alejandrobusi/Todo1-Ecommerce#15]
Corregir detalles de interfaz para que el sitio se vea correctamente, por ejemplo en la pagina de inicio queda demasiado espacio hacia la derecha de las cards

![image](https://user-images.githubusercontent.com/18445151/184384488-c5f54ef4-f5e7-4ef5-8a4f-18a0905a2b85.png)

**Comment by alejandrobusi** [comment]
Listoo :)
